Repository hub-usp-inovacao/platform, pull requests merged in 2023-05, with the labels that each got.

#108 Change cidade-sede multiple answers to one answer
  backend/app/models/company.rb
  backend/app/models/company_datum.rb
  backend/app/views/application_mailer/confirmation_company_update.html.erb
  backend/app/views/application_mailer/confirmation_company_update.text.erb
  backend/spec/models/company_datum_spec.rb
  backend/spec/models/company_spec.rb
  backend/spec/requests/company_spec.rb
  backend/spec/requests/company_updates_spec.rb
  frontend/components/CompanyForms/companyStep/Base.vue
  frontend/store/company_forms/company_data.js
Labels: WIP

#156 Add field "company nature" on company update form
  backend/app/models/company_datum.rb
  backend/app/views/application_mailer/confirmation_company_update.html.erb
  backend/config/locales/pt-br.yml
  backend/spec/models/company_datum_spec.rb
  frontend/components/CompanyForms/companyStep/Base.vue
  frontend/components/CompanyForms/inputs/MaskInput.vue
  frontend/components/CompanyForms/inputs/PairOfNumberAndText.vue
  frontend/plugins/services/update_company.js
  frontend/store/company_forms/company_data.js
Labels: frontend, backend-rails, formulário-atualização, review

#157 Add partner role to company update form
  backend/app/controllers/company_updates_controller.rb
  backend/app/models/partner.rb
  backend/app/views/application_mailer/confirmation_company_update.html.erb
  backend/app/views/application_mailer/confirmation_company_update.text.erb
  backend/spec/models/partner_spec.rb
  backend/spec/requests/company_updates_spec.rb
  frontend/components/CompanyForms/partnersStep/NewPartnerModal.vue
Labels: formulário-atualização, review

#172 Add logo upload in company form update
  backend/.gitignore
  backend/app/controllers/company_updates_controller.rb
  backend/app/models/about_company.rb
  backend/app/models/company.rb
  backend/app/views/application_mailer/confirmation_company_update.html.erb
  backend/config/routes.rb
  backend/public/uploads/logos/.keep
  backend/spec/models/about_company_spec.rb
  backend/spec/models/company_spec.rb
  backend/tmp/uploads/logos/.keep
  frontend/components/CompanyForms/companyStep/About.vue
  frontend/plugins/services/update_company.js
  frontend/store/company_forms/about.js
  frontend/store/company_forms/index.js
Labels: backend-rails, formulário-atualização, review

#176 Change "CIETEC" name to "Incubadora USP/IPEN"
  frontend/components/CompanyForms/IntroStep.vue
  frontend/components/CompanyForms/companyStep/Incubator.vue
Labels: WIP
